spring:
  application:
    name: config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/JerryDDDDD/spring-cloud-config
          search-paths: respo
          username: 569193365@qq.com
          password: 1314yzw..

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/